### ISSUE TITLE
Sound not working

### ISSUE THREAD

**Issue by sagar1garg** [doancongbang1991/mobileapp#1]
@doancongbang1991 

Sound doesn't seem to load for the game. Any solution?

**Comment by doancongbang1991** [comment]
Sound extensions are .ogg and .m4a not working on github pages. Please use your own host and make sure mime types configured. 
Please follow 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Configuring_servers_for_Ogg_media

**Comment by sagar1garg** [comment]
@doancongbang1991 mime types is correctly set and I tried it on localhost as well as on a hosted cloud service. There is no sound. Sounds in other games are working well. Problem is with only this game.

**Comment by doancongbang1991** [comment]
Please let me know what game is it. I'll check it

**Comment by sagar1garg** [comment]
@doancongbang1991  Pacman
